Define kernel.yama.ptrace_scope with lower priority.
Otherwise when building a new GCE image:
error: The unique option `boot.kernel.sysctl.kernel.yama.ptrace_scope'
is defined multiple times, in
`.../nixpkgs/nixos/modules/config/sysctl.nix' and
`.../nixos/maintainers/scripts/gce/../../../modules/virtualisation/google-compute-image.nix'.